package com.telino.avp.entity.auxil;

import java.time.ZonedDateTime;
import java.util.Date;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.MappedSuperclass;
import javax.persistence.Transient;

import org.bouncycastle.tsp.TimeStampToken;

import com.telino.avp.service.journal.TamponHorodatageService;

/**
 * Classe mere de log_event et log_archive
 * 
 * @author jwang
 *
 */
@MappedSuperclass
public abstract class Journal {

	// Timestamp for order purpose, generated by application server itself
	protected ZonedDateTime timestamp;

	protected String hash;

	// Timestamp may offre from other system
	protected ZonedDateTime horodatage;

	@Column(name = "timestamptoken")
	protected byte[] timestampTokenBytes;

	@Column(name = "logtype")
	protected String logType;

	//
	// Attributs d'utilisation Java
	//

	@Transient
	private String contenu;

	@Transient
	private TimeStampToken timestampToken;

	public Journal() {
		super();
	}

	public ZonedDateTime getTimestamp() {
		return timestamp;
	}

	public void setTimestamp(ZonedDateTime timestamp) {
		this.timestamp = timestamp;
	}

	public String getHash() {
		return hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	public ZonedDateTime getHorodatage() {
		return horodatage;
	}

	public void setHorodatage(ZonedDateTime horodatage) {
		this.horodatage = horodatage;
	}

	public void setHorodatage(Date horodatage) {
		this.horodatage = TamponHorodatageService.convertToSystemZonedDateTime(horodatage);
	}

	public byte[] getTimestampTokenBytes() {
		return timestampTokenBytes;
	}

	public void setTimestampTokenBytes(byte[] timestampTokenBytes) {
		this.timestampTokenBytes = timestampTokenBytes;
	}

	public String getLogType() {
		return logType;
	}

	public void setLogType(String logType) {
		this.logType = logType;
	}

	public String getContenu() {
		return contenu;
	}

	public void setContenu(String contenu) {
		this.contenu = contenu;
	}

	public TimeStampToken getTimestampToken() {
		return timestampToken;
	}

	public void setTimestampToken(TimeStampToken timestampToken) {
		this.timestampToken = timestampToken;
	}

	public abstract UUID getLogId();
}
